#
# Author: Giri Jeedigunta
# Git: https://github.com/giri-jeedigunta/java-spring-mongo-starter-reactive
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    name: app-deployment
    app: rest-app-java
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app-pod
      app: rest-app-java
  template:
    metadata:
      name: app-pod
      labels:
        name: app-pod
        app: rest-app-java
    spec:
      containers:
        - name: rest-app-java
          image: girijeedigunta/rest-app-java:latest
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    name: app-service
    app: rest-app-java
spec:
  selector:
    name: app-pod
    app: rest-app-java
  type: LoadBalancer
  ports:
    - targetPort: 4000
      port: 4000
